### ISSUE TITLE
Catering for Microsoft Extensions Logging

### ISSUE THREAD

**Issue by RemnantSoftware** [Shuttle/Shuttle.Core.Logging#3]
Hi Eben

First I want to thank you for Shuttle, it is a masterpiece!

MS has introduced a logging API that can work with a variety 3rd party logging providers ( for .NET Core and ASP.NET Core).
It also provides built-in logging providers but it will be great if a ILogger adapter can be implemented for Shuttle logging
to utilize this feature. 

Currently the following 3rd logging providers already created extensions for the MS logging factory:
elmah.io 
Gelf 
JSNLog 
KissLog.net 
Log4Net 
Loggr 
NLog 
Sentry
Serilog
Stackdriver 

It is also following the same pattern for Azure logging, example the Azure Application Insights provider.
This will also cut out the effort for you to write logging adapters (example log4Net), cause Shuttle will just ride on the abstract implementation of MS, thus the effort falls on 3rd parties to implement their solutions.

Kind regards
Neill

**Comment by eben-roux** [comment]
Hi Neill,

Thanks for the kind words :) - although, as you know, I *am* using some of your ideas in here ;)

I have created a new [repository](https://github.com/Shuttle/Shuttle.Core.Microsoft.Extensions.Logging) that implements the [Microsoft.Extensions.Loggin](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging?view=dotnet-plat-ext-5.0).

The [NuGet package](https://www.nuget.org/packages/Shuttle.Core.Microsoft.Extensions.Logging/) is also available.

Kind regards,
Eben
